### ISSUE TITLE
How can i change the description of all my posts in facebook. 

### ISSUE THREAD

**Issue by Deadterm1nator** [TissuePowder/YAFOT-Facebook#4]
When i upload a post with the frame it just appear the number of frame and timestamp, how can i edit the description and put some text, with the number of frames.

**Comment by Deadterm1nator** [comment]
![image](https://user-images.githubusercontent.com/88507580/129127634-cf7bbf10-e27f-489f-93d0-325a8ddf6c53.png)

**Comment by TissuePowder** [comment]
Right now you need to edit a .py file directly to add custom description. It's noted in the release information.

![Screenshot_2021_08_12__17-21-46](https://user-images.githubusercontent.com/39616942/129188975-0ea06cdd-fc24-4ed1-873e-7407aa0f4b82.png)

Edit the bot.py file in the src directory, as it says. Check the part here for example.
https://github.com/TissuePowder/YAFOT-Facebook/blob/master/src/bot.py#L53

There are already some description there commented out. Remove the '#' character to uncomment and edit them. Or you can copypaste the lines again and again for more description. I kind of abandoned the project, I will transfer the description editing option in a config file in later release. Test your output with --dry-run option, btw.

For the timestamp, if you aren't extracting the frames using ffmpeg with _-frame_pts 1_ option and renaming the files as the bot wants you, timestamp feature won't work properly.

**Comment by Deadterm1nator** [comment]
and how can i delete the "timestamps" from the posts?

**Comment by Deadterm1nator** [comment]
and how can i edit it, because im trying to putt my description in the place you say but it doesnt change anything

**Comment by TissuePowder** [comment]
I made a v0.2 release which now makes timestamping optional. If you don't pass the --use-timestamp option, bot will not try to parse timestamp from the filename and it won't appear in your post.

How did you change the description? You should edit it like the following. Removing the '#' character.
### Before editing bot.py file:
```
msg = (
        # f"Some anime\n"
        # f"Episode 01 of 12\n"
        f"Frame {current_frame_number:0{padding}} of {total_frames}"
        # Comment out the following line if you aren't using timestamp
        f"{timestamp_msg}"
        # f"\nTag: ABCXX_E1F{current_frame_number}"
    )
```
### After editing bot.py file:
```
msg = (
        f"Kamichu! Specials\n"
        f"Episode 01 of 12\n"
        f"Frame {current_frame_number:0{padding}} of {total_frames}"
        # Comment out the following line if you aren't using timestamp
        f"{timestamp_msg}"
        # f"\nTag: ABCXX_E1F{current_frame_number}"
    )
```

**Comment by Deadterm1nator** [comment]
It keeps appearing the same thing, frames and timestamp, and i already change all the things you said. 
![image](https://user-images.githubusercontent.com/88507580/129297878-a828d261-923a-492c-8a3d-4975952122ff.png)
![image](https://user-images.githubusercontent.com/88507580/129297927-887179c6-3979-4f94-97c0-7dd27db82649.png)

**Comment by Deadterm1nator** [comment]
i did all the things you said and it keeps saying frames and timestamps
![image](https://user-images.githubusercontent.com/88507580/129298073-da12a259-7f41-434c-b1c8-2f505a94a0aa.png)

**Comment by Deadterm1nator** [comment]
and i dont put the --use timestamp, and it put it on the posts

**Comment by TissuePowder** [comment]
That code doesn't seem right. Did you download the latest v0.2 release? Some part of code in the latest version does't exist in your screenshot. This should be the code in latest release.
```
def post_caption():
    newline = "\n"
    timestamp_msg = ""
    if timestamp:
        timestamp_msg = f"\nTimestamp: {timestamp}"
    # Add your desired post-caption here
    # It is recommended to execute the script in dry-run mode first to check the post captions and text formats
    msg = (
        # f"Some anime\n"
        # f"Episode 01 of 12\n"
        f"Frame {current_frame_number:0{padding}} of {total_frames}"
        # Comment out the following line if you aren't using timestamp
        f"{timestamp_msg}"
        # f"\nTag: ABCXX_E1F{current_frame_number}"
    )
    if config.verbose:
        print(f"Defined post caption:{newline}{msg}")

    return msg
```
If you are cloning the git, then make sure you do a git pull to the latest commit. Multiple files have been edited in the last release, you need to replace all the old files with newer ones.

Things should be solved if you are using latest version, but if you still can't make it work, then put a '#' character before the _f"{timestamp_msg}"_ line as the last resort.

**Comment by Deadterm1nator** [comment]
![image](https://user-images.githubusercontent.com/88507580/129359189-5c1d53ff-3d6f-4ba7-8e64-9607802246bc.png)
I already download the v2 and it keeps showing the frames and timestamps

**Comment by TissuePowder** [comment]
This shouldn't be possible. I really don't get what's happening. Could you use the bot to post one or two frames in facebook, then show me a screenshot of the post so that I can understand what's happening? You can blur out your page's name if you are concerned with privacy, I just want to see the captions.

**Comment by Deadterm1nator** [comment]
![image](https://user-images.githubusercontent.com/88507580/129360889-5bdda9e7-cccc-4888-9f5f-d871fe44381e.png)

**Comment by TissuePowder** [comment]
I can't reproduce this. This is the test result for me.

**Code:**
![Screenshot_2021_08_13__19-12-25](https://user-images.githubusercontent.com/39616942/129362842-142506c6-d1ed-47c0-8242-f578d19e6ce4.png)

**Command to run:**
![Screenshot_2021_08_13__19-13-39](https://user-images.githubusercontent.com/39616942/129362910-6e3f937e-c874-4657-bdb4-6760f684a3f6.png)

**Result:**
![Screenshot_2021_08_13__19-16-21](https://user-images.githubusercontent.com/39616942/129362969-81888193-cdbd-484a-ac54-d790a47a4756.png)

Did you save the old files in your system or program directory and forgot to delete them? Maybe those old files are still being used. Also check if your old files are cached somewhere or still being used instead of the new ones. Put the new files in a new/different folder, then directly run the yafot-facebook.py script from that folder.

**Comment by TissuePowder** [comment]
I can't reproduce this. This is the test result for me.

**Code:**
![Screenshot_2021_08_13__19-12-25](https://user-images.githubusercontent.com/39616942/129362842-142506c6-d1ed-47c0-8242-f578d19e6ce4.png)

**Command to run:**
![Screenshot_2021_08_13__19-28-19](https://user-images.githubusercontent.com/39616942/129364332-705bffa4-1f6e-4167-bb2b-c763e4d5b8a9.png)


**Result:**
![Screenshot_2021_08_13__19-16-21](https://user-images.githubusercontent.com/39616942/129362969-81888193-cdbd-484a-ac54-d790a47a4756.png)

Did you save the old files in your system or program directory and forgot to delete them? Maybe those old files are still being used. Also check if your old files are cached somewhere or still being used instead of the new ones. Put the new files in a new/different folder, then directly run the yafot-facebook.py script from that folder.

**Comment by Deadterm1nator** [comment]
You were right i had the old file, i delete it and put the new version, and all is perfect. Thank you so much.
