### ISSUE TITLE
Another page

### ISSUE THREAD

**Issue by Deadterm1nator** [TissuePowder/YAFOT-Facebook#5]
Hi what can i do if i want to make another frame page? i need to download the files again or with the same?

**Comment by TissuePowder** [comment]
No need to download the files again, there hasn't been any update or new version release since the last time you downloaded. For this kind of questions or help, it would probably be better if you just contact or message me through one of the frame pages I run. This issue section is for bugs, suggestions or technical questions.

**Comment by Deadterm1nator** [comment]
Ok, which page do i message you?

**Comment by TissuePowder** [comment]
Check the two pages mentioned in readme file. You can message me in any one of them, but Houseki no kuni would be better.
